import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import morgan from "morgan";
import { rateLimit } from "express-rate-limit";
import path from "node:path";
import { fileURLToPath } from "node:url";
import authRoutes from "./routes/authRoutes.js";
import eventRoutes from "./routes/eventRoutes.js";
import clubRoutes from "./routes/clubRoutes.js";
import lostItemRoutes from "./routes/lostItemRoutes.js";
import dashboardRoutes from "./routes/dashboardRoutes.js";
import miscRoutes from "./routes/miscRoutes.js";
import { errorHandler, notFound } from "./middlewares/error.js";

const app = express();
const dirname = path.dirname(fileURLToPath(import.meta.url));
app.set("trust proxy", 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
app.use(cors({ origin: process.env.CLIENT_URL || "http://localhost:5173", credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(morgan(process.env.NODE_ENV === "production" ? "combined" : "dev"));
app.use("/uploads", express.static(path.join(dirname, "uploads")));
app.use("/api/auth", rateLimit({ windowMs: 15 * 60 * 1000, limit: 100 }), authRoutes);
app.use("/api/events", eventRoutes);
app.use("/api/clubs", clubRoutes);
app.use("/api/lost-items", lostItemRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api", miscRoutes);
app.get("/api/health", (_req, res) => res.json({ success: true, service: "CampusHub API" }));
app.use(notFound);
app.use(errorHandler);

const port = Number(process.env.PORT || 5000);
if (process.env.NODE_ENV !== "test") app.listen(port, () => console.log(`CampusHub API listening on ${port}`));
export default app;
